services:
    django:
        build:
            dockerfile: "Dockerfile.django"
        ports:
            - "8000:8000"
        expose:
            - 8000
    react:
        build:
            dockerfile: "Dockerfile.react"
        links:
            - "django:django"
        ports:
            - "3000:3000"
        depends_on:
            - django