# Generated by Django 4.2.6 on 2023-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorknoten_vogelhaus', '0005_parameterrange_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=-1),
        ),
    ]
