# Generated by Django 4.2.6 on 2023-12-02 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorknoten_vogelhaus', '0006_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weather', models.CharField(max_length=64)),
                ('weather_description', models.CharField(max_length=128)),
                ('wind_speed', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorknoten_vogelhaus.location')),
            ],
        ),
    ]
