# Generated by Django 4.2.6 on 2023-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorknoten_vogelhaus', '0008_locationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='display_name',
            field=models.CharField(default='cake', max_length=256, unique=False),
            preserve_default=False,
        ),
    ]
