# Generated by Django 4.2.6 on 2023-12-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorknoten_vogelhaus', '0009_location_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='display_name',
        ),
        migrations.AddField(
            model_name='parameter',
            name='display_name',
            field=models.CharField(default='cake', max_length=256),
            preserve_default=False,
        ),
    ]
