# Generated by Django 4.2.6 on 2023-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorknoten_vogelhaus', '0011_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuredparameter',
            name='sensor',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='display_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
